AV-Blog/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AV_Blog.Helpers;
using AV_Blog.Models;
using PagedList;
using PagedList.Mvc;

namespace AV_Blog.Controllers
{
    [RequireHttps]

    public class BlogPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BlogPosts
        //[Authorize(Roles = "Admin, Moderator")]
        public ActionResult Index(int? page, string searchStr)
        {
            ViewBag.Search = searchStr;
            var blogList = IndexSearch(searchStr);

            int pageSize = 3; //specifies the number of posts per page 
            int pageNumber = (page ?? 1); //?? null coalescing operator

            var model = blogList.ToPagedList(pageNumber, pageSize);
            return View(model);
        }

        public IQueryable<BlogPost> IndexSearch(string searchStr)
        {
            IQueryable<BlogPost> result = null;
            if (searchStr != null)
            {
                result = db.BlogPosts.AsQueryable();
                result = result.Where(b => b.Title.Contains(searchStr) ||
                                           b.Body.Contains(searchStr) ||
                                           b.Comments.Any(c => c.CommentBody.Contains(searchStr) ||
                                                          c.Author.FirstName.Contains(searchStr) ||
                                                          c.Author.LastName.Contains(searchStr) ||
                                                          c.Author.DisplayName.Contains(searchStr) ||
                                                          c.Author.Email.Contains(searchStr)));
            }
            else
            {
                result = db.BlogPosts.AsQueryable();
            }
            return result.OrderByDescending(p => p.Created);
        }

        // GET: BlogPosts/Details/5
        public ActionResult Details(string slug)
        {
            //if (String.IsNullOrWhiteSpace(slug))
            //{
            //    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            //}
            BlogPost blogPost = db.BlogPosts.FirstOrDefault(b => b.Slug == slug);
            //if (blogPost == null)
            //{
            //    return HttpNotFound();
            //}
            return View(blogPost);
        }

        // GET: BlogPosts/Create
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            var blogPostCreate = db.BlogPosts.Create();
			return View(blogPostCreate);
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title,Body,Abstract,MediaURL,Published,Created,Updated")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var slug = StringUtilities.URLFriendly(blogPost.Title);
                if (slug != blogPost.Slug)
                {
                    if (String.IsNullOrWhiteSpace(slug))
                    {
                        ModelState.AddModelError("Title", "Invalid Title");
                        return View(blogPost);
                    }
                    if (db.BlogPosts.Any(p => p.Slug == slug))
                    {
                        ModelState.AddModelError("Title", "The title must be unique.");
                        return View(blogPost);
                    }

                    blogPost.Slug = slug;

                }

                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var justFileName = Path.GetFileNameWithoutExtension(fileName);
                    justFileName = StringUtilities.URLFriendly(justFileName);
                    fileName = $"{justFileName}_{DateTime.Now.Ticks}{Path.GetExtension(fileName)}";
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.MediaURL = "/Uploads/" + fileName;
                }
                blogPost.Created = DateTime.Now;
                db.BlogPosts.Add(blogPost);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blogPost);
        }

        // GET: BlogPosts/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Body,Slug,Abstract,MediaURL,Published,Created,Updated")] BlogPost blogPost, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                var slug = StringUtilities.URLFriendly(blogPost.Title);
                if (slug != blogPost.Slug)
                {
                    if (String.IsNullOrWhiteSpace(slug))
                    {
                        ModelState.AddModelError("Title", "Invalid Title");
                        return View(blogPost);
                    }

                    blogPost.Slug = slug;
                }

                if (ImageUploadValidator.IsWebFriendlyImage(image))
                {
                    var fileName = Path.GetFileName(image.FileName);
                    image.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blogPost.MediaURL = "/Uploads/" + fileName;
                }

                blogPost.Updated = DateTime.Now;
                db.Entry(blogPost).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");

            }
            return View(blogPost);
        }

        // GET: BlogPosts/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPost blogPost = db.BlogPosts.Find(id);
            if (blogPost == null)
            {
                return HttpNotFound();
            }
            return View(blogPost);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPost blogPost = db.BlogPosts.Find(id);
            db.BlogPosts.Remove(blogPost);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AV-Blog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx">

<head>
	<meta charset="utf-8">
	<title>The Code Cat Blog</title>

	<!-- mobile responsive meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- ** Plugins Needed for the Project ** -->
	<!-- Bootstrap -->
	<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
	<!-- slick slider -->
	<link href="~/Content/slick.css" rel="stylesheet" />
	<!-- themefy-icon -->
	<link href="~/Content/themify-icons.css" rel="stylesheet" />

	<!-- Main Stylesheet -->
	<link href="~/Content/style.css" rel="stylesheet" />
	<!--Paged List Stylesheet-->
	<link href="~/Content/PagedList.css" rel="stylesheet" />
	<!--Favicon-->
	<link rel="icon" href="~/favicon.ico" type="image/x-icon" />

</head>

<body>
	<!-- preloader -->
	<div class="preloader">
		<div class="loader">
			<span class="dot"></span>
			<div class="dots">
				<span></span>
				<span></span>
				<span></span>
			</div>
		</div>
	</div>
	<!-- /preloader -->

	<header class="navigation">
		<nav class="navbar navbar-expand-lg navbar-light">
			<a class="navbar-brand" href="https://avelezblog.azurewebsites.net/"><img class="img-fluid" src="~/Images/CodeCatLogo.png" alt="parsa"></a>
			<button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#navogation"
					aria-controls="navogation" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse text-center" id="navogation">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item">
						<a class="nav-link text-uppercase text-dark" @Html.ActionLink("Home", "Index", "Home")</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-uppercase text-dark" @Html.ActionLink("About", "About", "Home")</a>
					</li>
					@*<li class="nav-item">
			<a class="nav-link text-uppercase text-dark" href="category.html">Categories</a>
		</li>*@
					<li class="nav-item">
						<a class="nav-link text-uppercase text-dark" @Html.ActionLink("Contact", "Contact", "Home")</a>
					</li>
					<li class="text-uppercase text-dark">
						@Html.Partial("_LoginPartial")
					</li>
					<li class="nav navbar-nav navbar-right linkButton text-center" style="padding: 20px 20px">
						@if (ViewContext.HttpContext.User.IsInRole("Admin"))
						{
							@Html.ActionLink("CREATE", "Create", "BlogPosts")
						}
					</li>
					<li>
					</li>
				</ul>
			</div>
		</nav>
	</header>

	@RenderBody()

	<footer class="bg-secondary">
		<div class="section">
			<div class="container">
				<div class="row">
					<div class="col-md-3 col-sm-6 mb-4 mb-md-0">
						<a href="https://avelezblog.azurewebsites.net/"><img src="~/Images/CodeCatLogo.png" alt="persa" class="img-fluid"></a>
					</div>
					<div class="col-md-3 col-sm-6 mb-4 mb-md-0">
						<h6>Address</h6>
						<ul class="list-unstyled">
							<li class="font-secondary text-dark"></li>
							<li class="font-secondary text-dark">Chattanooga, TN</li>
						</ul>
					</div>
					<div class="col-md-3 col-sm-6 mb-4 mb-md-0">
						<h6>Contact Info</h6>
						<ul class="list-unstyled">
							<li class="font-secondary text-dark">Tel: 423-617-5220</li>
							<li class="font-secondary text-dark">Mail: avelez9882@gmail.com</li>
						</ul>
					</div>
					<div class="col-md-3 col-sm-6 mb-4 mb-md-0">
						<h6 class="text-center">Portfolio</h6>
						<ul class="list-inline d-inline-block">
							<li class="list-inline-item"><a href="https://av-portfolio.netlify.app" target="_blank" class="text-dark"><img src="~/Images/android-chrome-192x192.png"</a></li>
							@*<li class="list-inline-item"><a href="#" class="text-dark"><i class="ti-twitter-alt"></i></a></li>
							<li class="list-inline-item"><a href="#" class="text-dark"><i class="ti-linkedin"></i></a></li>
							<li class="list-inline-item"><a href="#" class="text-dark"><i class="ti-github"></i></a></li>*@
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="text-center pb-3">
			<p class="mb-0">
				Copyright ©
				<script>
					var CurrentYear = new Date().getFullYear()
					document.write(CurrentYear)</script> a theme by  <a href="https://themefisher.com/">themefisher.com</a>
					Modified by Angelica Velez 
			</p>
		</div>
	</footer>

	<!-- jQuery -->
	<script src="~/Scripts/jquery.min.js"></script>
	<!-- Bootstrap JS -->
	<script src="~/Scripts/bootstrap.min.js"></script>
	<!-- slick slider -->
	<script src="~/Scripts/slick.min.js"></script>
	<!-- masonry -->
	<script src="~/Scripts/masonry.js"></script>
	<!-- instafeed -->
	<script src="~/Scripts/instafeed.min.js"></script>
	<!-- smooth scroll -->
	<script src="~/Scripts/smooth-scroll.js"></script>
	<!-- headroom -->
	<script src="~/Scripts/headroom.js"></script>
	<!-- reading time -->
	<script src="~/Scripts/readingTime.min.js"></script>
	<script src="~/Scripts/jquery-3.2.1.min.js"></script>
	<!-- Main Script -->
	<script src="~/Scripts/script.js"></script>


	@RenderSection("scripts", required: false)
</body>
</html>